CREATE TABLE TB_CATEGORIA(
    CD_CATEGORIA INT,
    NM_CATEGORIA VARCHAR2(20)
);


CREATE TABLE TB_LIVRO(
    CD_LIVRO INT,
    TITULO VARCHAR(20),
    PRECO NUMERIC(10,2),
    CD_CATEGORIA INT
);

CREATE TABLE TB_ESTATISTICA(
    NM_CATEGORIA VARCHAR2(20),
    TOTAL_LIVROS INT,
    PRECO_MEDIO NUMERIC(10,2)
);
INSERT INTO TB_CATEGORIA VALUES (1,'ANIMES');
INSERT INTO TB_CATEGORIA VALUES (2,'AÇÃO');

INSERT INTO TB_LIVRO VALUES(1, 'PI', 5.6, 1);
INSERT INTO TB_LIVRO VALUES(2, 'AKAMEGAKILL', 10.6, 1);
INSERT INTO TB_LIVRO VALUES(3, 'AS AVENTURAS DE PI', 1.6, 2);
INSERT INTO TB_LIVRO VALUES(4, 'RAMBO', 5.4, 2);
INSERT INTO TB_LIVRO VALUES(5, 'MARIO', 4, 2);
INSERT INTO TB_LIVRO VALUES(9, 'CONTOS', 100, 1);

INSERT INTO TB_ESTATISTICA VALUES('ANIMES',2,3.5);
INSERT INTO TB_ESTATISTICA VALUES('AÇÃO',2,8.1);

SELECT * FROM TB_ESTATISTICA;
SELECT * FROM TB_LIVRO;
SELECT * FROM TB_CATEGORIA;

CREATE OR REPLACE TRIGGER TG_INSERT_ESTATISTICA
AFTER INSERT OR UPDATE OR DELETE ON TB_LIVRO
BEGIN
    DELETE tb_estatistica;

    INSERT INTO tb_estatistica
    SELECT C.NM_CATEGORIA, COUNT(L.CD_LIVRO), AVG(L.PRECO)
    FROM TB_LIVRO L 
    JOIN TB_CATEGORIA C
    ON l.cd_categoria = c.cd_categoria
    GROUP BY C.NM_CATEGORIA;  
END;