CREATE OR REPLACE PROCEDURE SP_INCLUI_FORNECEDOR(FORN IN VARCHAR2, NOME IN VARCHAR2, MENSAGEM OUT VARCHAR2)
AS
    ID NUMBER;
BEGIN
    ID := SQ_FORNECEDOR.nextval;
    INSERT INTO TB_FORNECEDOR(CD_FORNECEDOR, NM_FORNECEDOR, NM_CONTATO, DT_CADASTRO)
    VALUES(
    ID,
    FORN,
    NOME,
    SYSDATE
    );
    IF SQL%FOUND THEN
        MENSAGEM := 'CLIENTE ' || TO_CHAR(ID) || ' ADICIONADO';
    ELSE
        MENSAGEM := 'NÃO FOI POSSÍVEL ADICIONAR O CLIENTE';
    END IF;
END;

DECLARE
MSG VARCHAR2(100);
BEGIN
SP_INCLUI_FORNECEDOR('MANSÃO MAROMBA','KENDY',MSG);
DBMS_OUTPUT.PUT_LINE(MSG);
END;

SELECT * FROM TB_FORNECEDOR;

COMMIT;