CREATE TABLE TB_PRODUTO(
    CODIGO INT,
    DESCRICAO VARCHAR2(50),
    PRECO NUMBER(10,2)
);

CREATE SEQUENCE SQ_PRODUTO START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_INSERIR_CODIGO
BEFORE INSERT ON TB_PRODUTO
FOR EACH ROW
BEGIN
    :NEW.CODIGO := SQ_PRODUTO.NEXTVAL;
END;

INSERT INTO TB_PRODUTO (DESCRICAO, PRECO)
VALUES ('COCA-COLA', 2.00);

INSERT INTO TB_PRODUTO (CODIGO, DESCRICAO, PRECO)
VALUES (3,'COCA-COLA', 2.00);

SELECT * FROM TB_PRODUTO;
DELETE TB_PRODUTO;