DROP TABLE TB_FUNCIONARIO;

CREATE TABLE TB_FUNCIONARIO(
    MATRICULA INT,
    NOME VARCHAR2(20),
    SALARIO NUMBER(10,2)
);

CREATE OR REPLACE TRIGGER TG_RESTRINGE_REDUCAO
BEFORE UPDATE ON TB_FUNCIONARIO
FOR EACH ROW
BEGIN
    IF :NEW.SALARIO < :OLD.SALARIO THEN
        RAISE_APPLICATION_ERROR (-20000,'NAO PODE HAVER REDUCAO DE SALARIO');
    END IF;
END;

INSERT INTO TB_FUNCIONARIO
VALUES(1,'ERICLES',10000.00);

INSERT INTO TB_FUNCIONARIO
VALUES(2,'MILENA',5000.00);

UPDATE TB_FUNCIONARIO
SET salario = 1000
WHERE matricula = 1;