CREATE TABLE TB_FUNCIONARIO(
ID NUMBER(8) PRIMARY KEY,
MATRICULA VARCHAR2(100) NOT NULL,
NM_FUNCIONARIO VARCHAR2(100) NOT NULL,
SALARIO NUMBER(10,2) NOT NULL,
IMPOSTO NUMBER(10,2)NULL
)TABLESPACE USERS;

CREATE SEQUENCE SQ_FUNCIONARIO START WITH 1 INCREMENT BY 1;

INSERT INTO TB_FUNCIONARIO(ID, MATRICULA, NM_FUNCIONARIO, SALARIO)
VALUES( 
    SQ_FUNCIONARIO.nextval,
    '201900008177',
    'ERICLES',
    5000.50
    );
    
INSERT INTO TB_FUNCIONARIO(ID, MATRICULA, NM_FUNCIONARIO, SALARIO)
VALUES( 
    SQ_FUNCIONARIO.nextval,
    '201900008167',
    'MILENA',
    2000.00
    );
    
INSERT INTO TB_FUNCIONARIO(ID, MATRICULA, NM_FUNCIONARIO, SALARIO)
VALUES( 
    SQ_FUNCIONARIO.nextval,
    '201900008197',
    'JOANNE',
    10000.00
    );
    
INSERT INTO TB_FUNCIONARIO(ID, MATRICULA, NM_FUNCIONARIO, SALARIO)
VALUES( 
    SQ_FUNCIONARIO.nextval,
    '201900008179',
    'KENDY',
    1000.00
    );
    
INSERT INTO TB_FUNCIONARIO(ID, MATRICULA, NM_FUNCIONARIO, SALARIO)
VALUES( 
    SQ_FUNCIONARIO.nextval,
    '201900009177',
    'THIAGO',
    2000.00
    );
    
SELECT * FROM TB_FUNCIONARIO;

CREATE OR REPLACE PROCEDURE SP_CALCULAR_IMPOSTO(REN IN NUMBER, IMP OUT NUMBER)
AS
BEGIN
    IF REN < 1378.81 THEN
        IMP := 0;
    ELSIF REN < 2743.25 THEN
        IMP := (REN * 0.15) - 205.92;
    ELSE
        IMP := (REN * 0.275) -  548.82;
    END IF;
END;

DECLARE
    IMP NUMBER(10,2);
BEGIN
    sp_calcular_imposto(5000,IMP);
    dbms_output.put_line(IMP);
END;

DECLARE
CURSOR C_FUNCIONARIO IS SELECT * FROM TB_FUNCIONARIO;
R_FUNCIONARIO C_FUNCIONARIO%ROWTYPE;
IMP NUMBER;
BEGIN
    OPEN C_FUNCIONARIO;
    FETCH C_FUNCIONARIO INTO R_FUNCIONARIO;
    WHILE C_FUNCIONARIO%FOUND LOOP
        sp_calcular_imposto(R_FUNCIONARIO.SALARIO,IMP);
        dbms_output.put_line(IMP);
        UPDATE TB_FUNCIONARIO F
        SET IMPOSTO = IMP
        WHERE R_FUNCIONARIO.ID = F.ID;
        FETCH C_FUNCIONARIO INTO R_FUNCIONARIO;
    END LOOP;
    CLOSE C_FUNCIONARIO;
END;

SELECT * FROM TB_FUNCIONARIO;